# Generated by Django 3.2.7 on 2023-11-02 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inGamename', models.CharField(max_length=50)),
                ('discord', models.CharField(max_length=50)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newworldapi.factions')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=100)),
                ('tier', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Settlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlementName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('sold', models.BooleanField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newworldapi.items')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newworldapi.gameusers')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newworldapi.settlements')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('seen', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newworldapi.posts')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='newworldapi.gameusers')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newworldapi.gameusers')),
            ],
        ),
        migrations.AddField(
            model_name='gameusers',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newworldapi.servers'),
        ),
        migrations.AddField(
            model_name='gameusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
