# Generated by Django 3.2.7 on 2021-09-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newworldapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servers',
            old_name='ServerName',
            new_name='serverName',
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeStamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timeStamp',
            field=models.IntegerField(),
        ),
    ]
