# Generated by Django 3.2.7 on 2021-09-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newworldapi', '0002_auto_20210914_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='userId',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='posterUserid',
        ),
    ]
