# Generated by Django 3.2.7 on 2021-10-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newworldapi', '0004_messages_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='posterId',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='settlementId',
            new_name='settlement',
        ),
        migrations.AddField(
            model_name='posts',
            name='sold',
            field=models.BooleanField(null=True),
        ),
    ]
